name: Publish Docker Image

on:
  push:
    branches:
      - main  
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine Image Tag
      id: tag
      run: |
        # Try to find a Git tag, otherwise use the short commit hash
        TAG=$(git describe --tags --exact-match 2>/dev/null || git rev-parse --short HEAD)
        echo "Tag or Commit: $TAG"
        echo "::set-output name=image_tag::$TAG"
    
    - name: Build and Publish Docker Image
      working-directory: backend
      run: |
        # Build the Docker image and tag it with both the dynamic tag and 'latest'
        ./gradlew bootBuildImage \
          --imageName=ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }} \
          --imageName=ghcr.io/${{ github.repository }}:latest
          
    - name: Verify image
      run: docker images
